### ISSUE TITLE
Comentários IDE

### ISSUE THREAD

**Issue by osmarbraz** [EduardoDib234/ControleEmprestimo#13]
Remova comentários da IDE

src/main/java/view/FrmMenuRelatorio.java

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

Revise outros arquivos.

**Comment by C0mrad078** [comment]
Resolvido
