### ISSUE TITLE
Comentários

### ISSUE THREAD

**Issue by osmarbraz** [EduardoDib234/ControleEmprestimo#3]
Remove comentários que não são relevantes das classes.

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

Poste somente código depois de revisar e formatar.

**Comment by C0mrad078** [comment]
Resolvido
